Fix TypeError in PHP8
Current implementation causes an error in PHP8:

```
TypeError: Unsupported operand types: string + int
```

Using `is_numeric` instead of the additional of a 0 and `is_int` fixes the error.